#!/bin/sh
#store the argument passed to the script
final="$@"

#find where the 'sjtu_drone' is
pack_path=$(rospack find drone_gazebo)

#export the gazebo pathes
export GAZEBO_MODEL_PATH=$pack_path/models:$GAZEBO_MODEL_PATH 
export GAZEBO_RESOURCE_PATH=$pack_path:/usr/share/gazebo:/usr/share/gazebo-7:/usr/share/gazebo_models:$GAZEBO_RESOURCE_PATH
export GAZEBO_PLUGIN_PATH=$pack_path/plugins:$GAZEBO_PLUGIN_PATH

echo $final
echo $GAZEBO_MODEL_PATH
echo $GAZEBO_RESOURCE_PATH
echo $GAZEBO_PLUGIN_PATH

#call the client of Gazebo
gzclient --verbose
