camera/horizontal_fov: 103.2
camera/vertical_fov: 77.4

raycast/dr:     0.2
raycast/dphi:   10
raycast/dtheta: 10

system/bbx/r: 0.2 #0.75
system/bbx/overshoot: 0.25

aep/gain/r_min: 0
aep/gain/r_max: 5
aep/gain/zero: 25
aep/gain/lambda: 0.75
aep/gain/sigma_thresh: 0.2
aep/tree/extension_range: 1
aep/tree/max_sampling_radius: 10
aep/tree/initial_iterations: 15
aep/tree/cutoff_iterations: 30

daep/gain/beta: 0.5

rrt/min_nodes: 100

# bounding box: necessary to limit the simulation 
# scenario (smaller than actual gazebo scenario)
boundary/min: [-7.5, -7.5, 0.0]
boundary/max: [7.5, 7.5, 2]
boundary/volume: 450
res: 0.2

visualize_rays: false
visualize_tree: true
visualize_exploration_area: true
visualizeDFM: true

robot_frame: "fcu"
world_frame: "world"

