# MAP RESOLUTION:
RES: 0.2

# Environment Limit
env_x_min: -13.5
env_x_max: 14.7
env_y_min: -11.2
env_y_max: 16
env_z_min: 0
env_z_max: 2.5

# Map limits
boundary/min: [-13.5, -11.2, 0]
boundary/max: [14.7, 16, 2.5]

# Environment volume
volume: 1627.5

# Define Drone Size:
DRONE_X: 0.4
DRONE_Y: 0.4
DRONE_Z: 0.1


