# MAP RESOLUTION:
RES: 0.2

# Environment Limit
env_x_min: -2.5
env_x_max: 16.5
env_y_min: -8.8
env_y_max: 5.9
env_z_min: 0
env_z_max: 3

# Environment volume
volume: 798

# Map limits
boundary/min: [-2.5, -8.8, 0]
boundary/max: [16.5, 5.9, 3]

# Define Drone Size:
DRONE_X: 0.4
DRONE_Y: 0.4
DRONE_Z: 0.1


