# MAP RESOLUTION:
RES: 0.2

# Environment Limit
env_x_min: -6.5
env_x_max: 13.5
env_y_min: -16
env_y_max: 1.3
env_z_min: 0
env_z_max: 2.5

# Environment volume
volume: 865

# Map limits
boundary/min: [-6.5, -16, 0]
boundary/max: [13.5, 1.3, 2.5]

# Define Drone Size:
DRONE_X: 0.4
DRONE_Y: 0.4
DRONE_Z: 0.1


